### ISSUE TITLE
Newly added entries aren't handled properly

### ISSUE THREAD

**Issue by neotron** [auxym/gandi-ldns#2]
I had a config with a single entry. Needed to add a couple of additional aliases, and they weren't parsed. Fix is simple - don't exit the program as soon as a matching ip is found. Instead continue processing additional entries. Sorry for not doing a pull request - it's simple enough not to need one. 

```
diff --git a/gandi-ldns.py b/gandi-ldns.py
old mode 100644
new mode 100755
index 78634c9..f602ec1
--- a/gandi-ldns.py
+++ b/gandi-ldns.py
@@ -94,7 +94,7 @@ def main():
             current_ip = get_ip()
 
         if zone_ip.strip() == current_ip.strip():
-            sys.exit()
+            continue
         else:
             print('DNS Mistmatch detected: A-record: ',
                   zone_ip, ' WAN IP: ', current_ip)
```

**Comment by auxym** [comment]
Fixed, thank you!
