### ISSUE TITLE
How to use multiple a_name in a single config file

### ISSUE THREAD

**Issue by ramzcode** [auxym/gandi-ldns#3]
Hi this is really good.

I am looking for if a single config file can be used to update multiple a_name records. Is there a way that this code can do it ? please advice thanks in advance

**Comment by auxym** [comment]
Haven't touched this code in years! Glad people still find it useful.

had a quick look at the code and it loops over config sections, so you should be able to do something like this in the config:

```ini
[root]
apikey = xxxxxxxxxxxxxxxxxxxxxxxx
domain = example.com

a_name = @
ttl = 10800
api = https://dns.api.gandi.net/api/v5/
host = localhost

[www]
apikey = xxxxxxxxxxxxxxxxxxxxxxxx
domain = example.com

a_name = www
ttl = 10800
api = https://dns.api.gandi.net/api/v5/
host = localhost
```

Please try it and let me know if it works.

**Comment by ramzcode** [comment]
Great !! it does as you said. Thanks a lot
